open-telemetry/opentelemetry-java-examples

- website_docs/automatic_instrumentation.md
Continuation of https://github.com/open-telemetry/opentelemetry-java/pull/3974
Contributes to open-telemetry/opentelemetry.io#972
> Add automatic instrumentation page to website docs

- website_docs/manual_instrumentation.md
Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/973
> Add section to get the current span

- website_docs/automatic_instrumentation.md
- website_docs/manual_instrumentation.md
> Fix broken links

- prometheus/build.gradle
- prometheus/src/main/java/io/opentelemetry/example/prometheus/ExampleConfiguration.java
- prometheus/src/main/java/io/opentelemetry/example/prometheus/PrometheusExample.java
good exmaple, but it's has a little difficult to find.
but PromethusExample seems to be misleading, i have same issue for open-telemetry/opentelemetry-java#4032
I think this commit should solve the problem, and the code is clearer than before.
> replace PrometheusCollector with PrometheusHttpServer open-telemetry/opentelemetry-java#4032

- build.gradle
- grpc/README.md
- prometheus/README.md
> Update to v1.12.0

- autoconfigure/README.md
> Update docs for otel.metrics.exporter

- prometheus/Dockerfile
- prometheus/README.md
- prometheus/docker-compose.yml
- prometheus/prometheus.yml
> Fix prometheus networking by using docker compose

- .github/workflows/gradle-wrapper-validation.yml
> Add gradle wrapper validation

- build.gradle
- grpc/src/main/java/io/opentelemetry/example/grpc/HelloWorldClient.java
- grpc/src/main/java/io/opentelemetry/example/grpc/HelloWorldClientStream.java
- grpc/src/main/java/io/opentelemetry/example/grpc/HelloWorldServer.java
- http/src/main/java/io/opentelemetry/example/http/HttpServer.java
- javaagent/src/main/java/io/opentelemetry/example/javagent/Controller.java
> Compile examples against Java 8

- build.gradle
- log-appender/src/main/java/io/opentelemetry/example/logappender/Application.java
- log-appender/src/main/resources/log4j2.xml
- log-appender/src/main/resources/logback.xml
New features demo'd:
- Recording exceptions
- Capturing thread attributes
- Capturing slf4j key value pairs (enabled by [this recent change](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/8074))
> Demonstrate more log appender features

- .github/workflows/reusable-workflow-notification.yml
oops, #127 added a workflow that depends on this
> Add missing reusable workflow

- .github/workflows/update-gradle-wrappers-daily.yml
> Fix gradle wrapper update CLA issue

- README.md
Minor change to fix a link in the readme (I got pretty confused :D)
> Minor: Fix link in readme

- .github/workflows/update-gradle-wrappers-daily.yml
Resolves #143
Applies both https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/8849 and https://github.com/open-telemetry/opentelemetry-java/pull/5591
> Fix update gradle workflow

- metrics/src/main/java/io/opentelemetry/example/metrics/HistogramExample.java
Pretty silly, but maybe useful.
> Add a Histogram example

- .github/workflows/build.yml
- settings.gradle
hopefully will give more info on why #185 is failing...
> Publish build scans to ge.opentelemetry.io

- build.gradle
- http/build.gradle
- http/src/main/java/io/opentelemetry/example/http/HttpClient.java
- jaeger/build.gradle
- jaeger/src/main/java/io/opentelemetry/example/jaeger/ExampleConfiguration.java
- log-appender/build.gradle
- log-appender/src/main/java/io/opentelemetry/example/logappender/Application.java
- metrics/src/main/java/io/opentelemetry/example/metrics/HistogramExample.java
- otlp/build.gradle
- otlp/src/main/java/io/opentelemetry/example/otlp/ExampleConfiguration.java
- prometheus/build.gradle
- prometheus/src/main/java/io/opentelemetry/example/prometheus/ExampleConfiguration.java
- zipkin/build.gradle
- zipkin/src/main/java/io/opentelemetry/example/zipkin/ExampleConfiguration.java
Update to the latest upstream version.
> Update upstream version

- .github/renovate.json5
> Tell Renovate to update OTel alpha packages

- .github/workflows/codeql-daily.yml
> Add CodeQL

- README.md
> Include contrib maintainers/approvers

- otlp/README.md
- otlp/build.gradle.kts
This makes it a bit easier to run the example
> Add the application plugin to the otlp example

- .github/renovate.json5
I think the build might pass if #355 and #354 were grouped? Or at least that would give us more of a chance to help them along....
> Group protobuf deps into one PR

- build.gradle.kts
- doc-snippets/exporters/build.gradle.kts
- doc-snippets/getting-started/build.gradle.kts
- doc-snippets/spring-starter/build.gradle.kts
- spring-native/build.gradle.kts
follow up to https://github.com/open-telemetry/opentelemetry.io/pull/4848
> simplify BOM imports

- build.gradle.kts
- declarative-configuration/otel-sdk-config.yaml
- doc-snippets/configuration/src/main/java/otel/SdkMeterProviderConfig.java
- doc-snippets/configuration/src/main/java/otel/ViewConfig.java
- javaagent/sdk-config.yaml
Do not merge until release of `opentelemetry-java-instrumentation` and removal of snapshot dependency.
> Add cardinality limit demonstration

- doc-snippets/configuration/src/main/java/otel/SdkMeterProviderConfig.java
From PR feedback: https://github.com/open-telemetry/opentelemetry.io/pull/5610#discussion_r1843007447
> Rename variable for improved readability

- .github/workflows/build.yml
- settings.gradle.kts
TODO delete `GRADLE_ENTERPRISE_ACCESS_KEY` github action secret after merging this
> Update develocity configuration

- doc-snippets/api/src/main/java/otel/ContextUsage.java
Related to https://github.com/open-telemetry/opentelemetry.io/issues/5753
> Fix ContextUsage snippet

- .github/workflows/build.yml
- .github/workflows/gradle-wrapper-validation.yml
(also, this makes OSSF scorecard happy, which is why we did it in other Java repos)
> Sync workflow setup with other Java repos

- .github/renovate.json5
- javaagent/Dockerfile
- logging-k8s-stdout-otlp-json/Dockerfile
- prometheus/Dockerfile
Resolves
- https://github.com/open-telemetry/opentelemetry-java-examples/security/code-scanning/27
- https://github.com/open-telemetry/opentelemetry-java-examples/security/code-scanning/28
- https://github.com/open-telemetry/opentelemetry-java-examples/security/code-scanning/29
> Pin eclipse temurin

- declarative-configuration/build.gradle.kts
- doc-snippets/api/build.gradle.kts
- doc-snippets/configuration/build.gradle.kts
- doc-snippets/exporters/build.gradle.kts
- doc-snippets/getting-started/build.gradle.kts
- doc-snippets/spring-starter/build.gradle.kts
- micrometer-shim/build.gradle.kts
- spring-native/build.gradle.kts
- telemetry-testing/build.gradle.kts
> Add explicit toolchain version to all modules
