open-telemetry/opentelemetry-java-examples

website_docs/automatic_instrumentation.md
website_docs/instrumentation_examples.md
website_docs/manual_instrumentation.md

@cartermp:
- This PR does a cleanup of the markdown. Mainly, line-wrapping paragraphs (so that git diffs work better), and adding a blank line where appropriate between markdown elements (like a header or code-block and a paragraph).
- There is no change in content
- I've added a `linkTitle` to the instrumentation page that shortens the title (since these pages are already under the **Instrumentation** section of the website docs.
I'd show you a preview if I could, but I can't 😉 
/cc @austinlparker

Markdown cleanup and add linkTitles

---

.github/workflows/pr-build.yml
README.md
jaeger/README.md
jaeger/build.gradle
jaeger/src/main/java/io/opentelemetry/example/jaeger/ExampleConfiguration.java
jaeger/src/main/java/io/opentelemetry/example/jaeger/JaegerExample.java
logging/src/main/java/io/opentelemetry/example/logging/ExampleConfiguration.java
logging/src/main/java/io/opentelemetry/example/logging/LoggingExporterExample.java
metrics/src/main/java/io/opentelemetry/example/metrics/DoubleCounterExample.java
metrics/src/main/java/io/opentelemetry/example/metrics/LongCounterExample.java
otlp/build.gradle
otlp/docker/docker-compose.yaml
otlp/src/main/java/io/opentelemetry/example/otlp/ExampleConfiguration.java
otlp/src/main/java/io/opentelemetry/example/otlp/OtlpExporterExample.java
sdk-usage/src/main/java/io/opentelemetry/sdk/example/ConfigureSpanProcessorExample.java
sdk-usage/src/main/java/io/opentelemetry/sdk/example/ConfigureTraceExample.java
zipkin/README.md
zipkin/src/main/java/io/opentelemetry/example/zipkin/ExampleConfiguration.java

- Reapply changes from [PR #4041](https://github.com/open-telemetry/opentelemetry-java/pull/4041) which were lost in the port (my bad)
- Fix typo in readme 
- Use `LoggingMetricExporter.create()` instead of deprecated `new LoggingMetricExporter`
- Use `openzipkin/zipkin:latest` image instead of `openzipkin/zipkin:2.21`
- Fix error in `sdk-usage` example causing span limits to not be applied 
- Take advantage of metrics being available in `GlobalOpenTelemetry` to simplify some stuff
- Fix github action so build actually runs

Various minor cleanup of examples

---

build.gradle

Update to reflect latest [release](https://github.com/open-telemetry/opentelemetry-java/releases/tag/v1.10.1).

Bump examples to 1.10.1

---

micrometer-shim/src/main/java/io/opentelemetry/example/micrometer/Controller.java

Was playing around with the micrometer example and realized that adding `@Timed` to the controller method stomps the automatic instrumentation of the controller method that results in metrics named `http.server.requests`.
Moving the annotation to another method.

Move @Timed annotation to another method

---

micrometer-shim/build.gradle
micrometer-shim/src/main/java/io/opentelemetry/example/micrometer/Application.java
micrometer-shim/src/main/java/io/opentelemetry/example/micrometer/Controller.java
micrometer-shim/src/main/java/io/opentelemetry/example/micrometer/Service.java

Was doing some investigation into how micrometer-shim works with exemplars and noticed that the `@Timed` annotation on the `micrometer-shim` example didn't work 😬. This fixes it.

Fix @Timed annotation for micrometer-shim

---

jaeger/README.md
jaeger/build.gradle
jaeger/src/main/java/io/opentelemetry/example/jaeger/ExampleConfiguration.java

Jaeger supports [OTLP](https://www.jaegertracing.io/docs/1.39/deployment/#collector), and there's an [effort](https://github.com/open-telemetry/opentelemetry-specification/pull/2858) to deprecate the jaeger exporter, so it seems appropriate to demonstrate SDK w/ OTLP exporter to Jaeger backend.

Update jaeger example to export over OTLP

---

build.gradle
otlp/src/main/java/io/opentelemetry/example/otlp/ExampleConfiguration.java
otlp/src/main/java/io/opentelemetry/example/otlp/OtlpExporterExample.java
prometheus/README.md
prometheus/build.gradle
prometheus/src/main/java/io/opentelemetry/example/prometheus/ExampleConfiguration.java
prometheus/src/main/java/io/opentelemetry/example/prometheus/PrometheusExample.java

Add an example of using the prometheus exporter to produce prometheus exemplars.
This PR does the following:
* Add tracerprovider initialization with a logging exporter
* Add trace instrumentation, which creates a span each loop
* Use a counter and histogram metric, instead of a gauge for the example.  Instrumentation is taken from the OTLP example.
If I curl the endpoint using OpenMetrics, I can see exemplars
`curl -H 'Accept: application/openmetrics-text; version=1.0.0; charset=utf-8' http://localhost:19090/metrics`
```
super_timer_count{otel_scope_name="io.opentelemetry.example.prometheus"} 219.0 1676324922.849
super_timer_sum{otel_scope_name="io.opentelemetry.example.prometheus"} 219088.0 1676324922.849
super_timer_bucket{otel_scope_name="io.opentelemetry.example.prometheus",le="0.0"} …
```

Add prometheus exemplar example

---

README.md
javaagent/docker-compose.yml
log-appender/README.md
log-appender/build.gradle
log-appender/docker-compose.yml
log-appender/otel-config.yaml
log-appender/src/main/java/io/opentelemetry/example/logappender/Application.java
log-appender/src/main/resources/log4j2.xml
log-appender/src/main/resources/logback.xml
settings.gradle

Adding functional examples demonstrating the log4j and logback appenders.
Partially motivated by the goal of [stabilizing log bridge API and SDK](https://github.com/open-telemetry/opentelemetry-specification/issues/2911), partially to make it abundantly how to use our log solutions.

Add log appender example

---

.github/workflows/update-gradle-wrappers-daily.yml

The bot uses a fixed account name: https://github.com/gradle-update/update-gradle-wrapper-action/blob/f6ef81d9b8e038607556c1144ec043805f1a70cc/src/tasks/main.ts#L97C38-L98
I will open a ticket to see about getting that bot account added to EasyCLA bot account list, but would like to merge this and re-generate the PR so I can reference the open (but failing EasyCLA) PR when making that request.

Revert "Fix gradle wrapper update CLA issue (#133)"

---

kotlin-extension/README.md
kotlin-extension/build.gradle
kotlin-extension/src/main/kotlin/io/opentelemetry/example/kotlinextension/Application.kt
kotlin-extension/src/main/kotlin/io/opentelemetry/example/kotlinextension/CoroutineContextExample.kt
settings.gradle

This is an example of how to use the `Context.asContextElement` extension function provided in the OTel Java [Kotlin extension library](https://github.com/open-telemetry/opentelemetry-java/tree/main/extensions/kotlin) in order to preserve a Span context across a coroutine, even if its thread changes.

Kotlin extension - coroutines example

---

metrics/build.gradle
metrics/src/main/java/io/opentelemetry/example/metrics/DoubleCounterExample.java
metrics/src/main/java/io/opentelemetry/example/metrics/GaugeExample.java
metrics/src/main/java/io/opentelemetry/example/metrics/HistogramExample.java
metrics/src/main/java/io/opentelemetry/example/metrics/LongCounterExample.java
settings.gradle

I lost track of the fact that I had already submitted the histogram example. So anyway, this updates it a little bit to include custom buckets. I'm not stoked on the cast required in the bucket example, but I think it's all we have right now. Happy to remove it if we think it's premature.
I also changed the other examples to use the autoconfigured SDK so that folks can actually run them in their IDE without getting the noop implementations.

Rework metrics examples

---

.github/workflows/build.yml
.github/workflows/codeql-daily.yml

See <https://github.com/gradle/gradle-build-action/blob/main/README.md>:
> As of `v3` this action has been superceded by `gradle/actions/setup-gradle`.
> Any workflow that uses `gradle/gradle-build-action@v3` will transparently delegate to `gradle/actions/setup-gradle@v3`.
>
> Users are encouraged to update their workflows, replacing:
> ```
> uses: gradle/gradle-build-action@v3
> ```
>
> with
> ```
> uses: gradle/actions/setup-gradle@v3
> ```
>
> See the [setup-gradle documentation](https://github.com/gradle/actions/tree/main/setup-gradle) for up-to-date documentation for `gradle/actions/setup-gradle`.

migrate gradle/gradle-build-action to gradle/actions/setup-gradle

---

autoconfigure/README.md

The default logs exporter is otlp which is not configured in this example.
This PR sets the default logs exporter to `logging` the same way it is being set for the traces and metrics.

Fix autoconfigure example

---

spring-native/README.md
spring-native/build.gradle.kts
spring-native/collector-spring-native-config.yaml
spring-native/docker-compose.yml
spring-native/src/main/java/io/opentelemetry/example/graal/Application.java
spring-native/src/main/resources/application.properties

https://github.com/open-telemetry/opentelemetry-java-examples/pull/227 also shows RuleBasedRoutingSampler, but using the new config file format.

update spring native example and show AutoConfigurationCustomizerProvider

---

metrics/src/main/java/io/opentelemetry/example/metrics/ViewExample.java

Added a few examples for configuring Views:
- Given a meter `customer_email_change` that is recorded with three attributes: `environment`, `region`, and `service`, use a view to filter out all attributes except `environment`
- Given a meter `http_requests_active`, use a view that renames it to `http.client.active_requests`
- Given a meter `cpu.bad`, use a view to drop that metric entirely

add view examples

---

metrics/build.gradle.kts
metrics/src/main/java/io/opentelemetry/example/metrics/ExponentialHistogramExample.java

Closes #319 
Created an example that configures two histograms to use the `base2ExponentialBucketHistogram` aggregation, one that uses the defaults, and another that sets a custom `maxScale`.

Exponential histogram example

---

log-appender/docker-compose.yml
log-appender/otel-config.yaml

**Description**: When using a new version of the collector image, using localhost instead of 0.0.0.0 would cause the host to be unable to report logs to the container, which was resolved by referring to this [issue](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/34394)
The logs are now printed properly!

Fix log-append collector can not output logs problem.

---

javaagent/collector-config.yaml

The Java agent example is broken:
```
app-1        | [otel.javaagent 2024-09-10 15:07:14:681 +0000] [OkHttp http://collector:4318/...] ERROR io.opentelemetry.exporter.internal.http.HttpExporter - Failed to export logs. The request could not be executed. Full error message: Failed to connect to collector/172.21.0.2:4318
app-1        | java.net.ConnectException: Failed to connect to collector/172.21.0.2:4318
app-1        |  at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
```
This PR fixes it.

Fix Java agent example

---

javaagent/collector-config.yaml
log-appender/otel-config.yaml
otlp/docker/otel-collector-config-demo.yaml
spring-native/collector-spring-native-config.yaml

This exporter has been replaced by the debug exporter and will be removed soon. Related to https://github.com/open-telemetry/opentelemetry-collector/pull/11037

fix: update references to logging exporter

---

otlp/docker/otel-collector-config-demo.yaml

Fixes #372 
Jaeger accepts OTLP on port 4317
This fix eliminates the error:
> error   exporterhelper/queue_sender.go:101      Exporting failed. Dropping data.        {"kind": "exporter", "data_type": "traces", "name": "otlp/jaeger", "error": "not retryable error: Permanent error: rpc error: code = Unimplemented desc = unknown service opentelemetry.proto.collector.trace.v1.TraceService", "dropped_items": 2}
And can see traces with this fix:

Update jaeger port for OTLP exporter

---

doc-snippets/api/build.gradle.kts
doc-snippets/api/src/main/java/otel/AsyncCounterUsage.java
doc-snippets/api/src/main/java/otel/AsyncGaugeUsage.java
doc-snippets/api/src/main/java/otel/AsyncUpDownCounterUsage.java
doc-snippets/api/src/main/java/otel/AttributesUsage.java
doc-snippets/api/src/main/java/otel/BaggageUsage.java
doc-snippets/api/src/main/java/otel/ContextUsage.java
doc-snippets/api/src/main/java/otel/CounterUsage.java
doc-snippets/api/src/main/java/otel/ExtractContextUsage.java
doc-snippets/api/src/main/java/otel/GaugeUsage.java
doc-snippets/api/src/main/java/otel/GlobalOpenTelemetryUsage.java
doc-snippets/api/src/main/java/otel/HistogramUsage.java
doc-snippets/api/src/main/java/otel/InjectContextUsage.java
doc-snippets/api/src/main/java/otel/LogRecordUsage.java
doc-snippets/api/src/main/java/otel/NoopUsage.java
doc-snippets/api/src/main/java/otel/OpenTelemetryUsage.java
doc-snippets/api/src/main/java/otel/ProvidersAndScopes.java
doc-snippets/api/src/main/java/otel/SemanticAttributesUsage.java
doc-snippets/api/src/main/java/otel/SpanAndContextUsage.java
doc-snippets/api/src/main/java/otel/SpanUsage.java
doc-snippets/api/src/main/java/otel/UpDownCounterUsage.java
doc-snippets/api/src/main/java/otel/Util.java
settings.gradle.kts

Code snippets support opentelemetry.io PR: https://github.com/open-telemetry/opentelemetry.io/pull/5276

Add api usage snippets

---

doc-snippets/api/src/main/java/otel/AsyncCounterUsage.java
doc-snippets/api/src/main/java/otel/AsyncGaugeUsage.java
doc-snippets/api/src/main/java/otel/AsyncUpDownCounterUsage.java
doc-snippets/api/src/main/java/otel/ContextUsage.java
doc-snippets/api/src/main/java/otel/GaugeUsage.java

PR feedback from @jaydeluca  on https://github.com/open-telemetry/opentelemetry.io/pull/5276

Fix API usage typos

---

javaagent/src/main/java/io/opentelemetry/example/javagent/Controller.java

The `./javaagent` example uses a Spring boot application, and spring boot's default log implementation is logback. The application uses the log4j API in application logging, which works, but is suboptimal. I discovered this when I tried to enable various experimental features in `opentelemetry-java-instrumentation`'s logback appender instrumentation and found that they didn't work. Apparently the context required to add things like thread and code calling information is lost when log4j is translated to slf4j to logback.
Switching the application logging to slf4j fixes the issue.

Use slf4j instead of log4j in javaagent example

---

javaagent/Dockerfile
javaagent/build.gradle.kts

Tried running the example and got this error during runtime:
```
java.lang.UnsupportedClassVersionError: org/springframework/boot/loader/launch/JarLauncher has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```
The error message indicates that the JarLauncher class has been compiled with Java 17 (class file version 61.0), but we are trying to run it with Java 11 (class file version 55.0). To resolve this issue, we need to use a Java 17 runtime in your Dockerfile.
I tried updating the image to eclipse-temurin:17-jre, but then saw this error message:
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: io/opentelemetry/example/javagent/Application has been …
```

chore: update javaagent base image to eclipse-temurin:17-jre

---

http/src/main/java/io/opentelemetry/example/http/HttpServer.java

Clean up ExtendedSpanBuilder call chain in HTTP Server Example according to merged: https://github.com/open-telemetry/opentelemetry-java/pull/6514

Clean up ExtendedSpanBuilder call chain in HTTP Server Example

---

resource-detection-gcp/README.md
resource-detection-gcp/build.gradle.kts
resource-detection-gcp/k8s/job.yaml

Updates the GCP Resource detection sample:
- Use Google Cloud Artifact Registry instead of Google Cloud Container Registry (now deprecated).
- Updates `job.yaml` to set proper environment variables so the following attributes can be detected by OpenTelemetry:
- `container.name`
- `k8s.pod.name`
- `k8s.namespace.name`
- Bumped the gcp-resource-detector dependency version.
- Add cleanup instructions.
Manually ran the sample following the updated instructions.

Update GCP resource detection sample

---

.github/renovate.json5

See https://github.com/open-telemetry/opentelemetry-java-examples/pull/561#discussion_r1904383603

Tell renovate to update contrib -alpha artifacts

---

doc-snippets/configuration/src/main/java/otel/OtlpAuthenticationConfig.java

Related to https://github.com/open-telemetry/opentelemetry.io/pull/5866

Demonstrate OTLP exporter programmatic authentication

---

.github/renovate.json5
.github/scripts/run-oats-tests.sh
.github/workflows/oats-tests.yml
logging-k8s-stdout-otlp-json/k8s/lgtm.yaml

Fixes https://github.com/open-telemetry/opentelemetry-java-examples/pull/662
As a second step, fix the issue with the latest LGTM version

update oats, pin LGTM version

---

.github/renovate.json5

Related to #160 
> Renovate failed to look up the following dependencies: Failed to look up docker package dice.
> Files affected: logging-k8s-stdout-otlp-json/k8s/dice.yaml
This image is built locally via the [k3d.sh script](https://github.com/open-telemetry/opentelemetry-java-examples/blob/main/logging-k8s-stdout-otlp-json/k3d.sh) and is not pulled from a registry

Ignore locally built dice image in renovate

---

.github/workflows/build.yml
declarative-configuration/otel-sdk-config.yaml

The declarative config example was broken. I fixed it and added a github action step to run it on PRs so we'll get alerted to this in the future.
This example was failing with:
> Task :opentelemetry-examples-declarative-configuration:run FAILED
Exception in thread "main" io.opentelemetry.api.incubator.config.DeclarativeConfigException: Unable to parse configuration input stream
at io.opentelemetry.sdk.extension.incubator.fileconfig.DeclarativeConfiguration.parse(DeclarativeConfiguration.java:142)
at io.opentelemetry.sdk.extension.incubator.fileconfig.DeclarativeConfiguration.parseAndCreate(DeclarativeConfiguration.java:86)
at io.opentelemetry.examples.fileconfig.Application.main(Application.java:31)
Caused by: java.lang.IllegalArgumentException: Cannot construct instance of …

Fix declarative configuration example

---

doc-snippets/spring-starter/src/main/java/otel/TracedClass.java

- Added missing `@WithSpan` annotation to `tracedMethodWithAttribute` method in `TracedClass.java`
After this PR is merged, I would like to fix the below document.
https://opentelemetry.io/docs/zero-code/java/spring-boot-starter/annotations/

fix: missing annotation in Annotation example

---

.github/workflows/issue-management-stale-action.yml

Port of https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/14853

Make stale issue automation jobs mutually exclusive
